### ISSUE TITLE
Validate AWS region on cluster creation

### ISSUE THREAD

**Issue by gjoseph92** [coiled/feedback#121]
By not reading the [docs](https://docs.coiled.io/user_guide/backends_aws.html#backend-options) carefully enough, I missed the fact that `us-west-2` is not yet a supported region. However, `ValueError: Unable to create cluster: No VPC subnets available` was not a very clear error to help figure that out. [This slack thread](https://coiled-users.slack.com/archives/C0195GJKQ1G/p1612455761088700) answered the question, but since the list of supported regions is pretty well-known, it would be nice to give users a more specific error message, including the list of supported regions they could use instead.

**Comment by FabioRosado** [comment]
Hello @gjoseph92, thank you for your feedback!

Alex, from our engineering team is currently working on this issue. Soon, we will be able to throw a better error since we will run some validation on the region that users specify and return a more informative error message.

I hope this hasn't caused any major issues for you when using Coiled. Please let me know if you need help with anything or if you have any feedback that could help us improve the user experience 😄

**Comment by jrbourbeau** [comment]
Thanks for testing things out @gjoseph92! Good to see you here : )

**Comment by dantheman39** [comment]
In fact, @gjoseph92 we _just_ deployed this, so now you should get an error saying `Unable to create cluster: Unsupported region. We currently support these AWS regions: ['us-east-1', 'us-east-2', 'us-west-1', 'eu-central-1', 'eu-west-2']`

**Comment by gjoseph92** [comment]
Yup, got it! `Unsupported region. We currently support these AWS regions: ['us-east-1', 'us-east-2', 'us-west-1', 'eu-central-1', 'eu-west-2']`

That's great, thanks for the quick turnaround.

**Comment by mrocklin** [comment]
I'm curious, what stops us from supporting all regions?  I would expect us
to be able to create these resources on the fly.
