### ISSUE TITLE
Cluster metadata issues

### ISSUE THREAD

**Issue by ericdill** [coiled/feedback#13]
![image](https://user-images.githubusercontent.com/6223243/82927446-b9b2f500-9f4e-11ea-915f-e714fdf091fe.png)

Seems like the dashboard link has a `tcp` protocol instead of http, so the link doesn't work. Also seems like the Dask link has double `tcp://` prepended

**Comment by mrocklin** [comment]
Hrm, thanks for raising.  There is a historical reason why this is the way it is, but it's being blown away soonish.  

Note to devs. I think that we probably want to pull this information from the data that the scheduler is sending back to Django, rather than from the backends.  @necaris is working on exposing this information now, so cc'ing him so that he is aware of both this use case and this current failing UI.

**Comment by ericdill** [comment]
Additionally, the port for the dashboard is 8787, not 8786

**Comment by mrocklin** [comment]
There is a reason why I encouraged you to wait a few days before trying things out :)

**Comment by shughes-uk** [comment]
We live in the future now and have https secured scheduler dashboards! Woo!
