### ISSUE TITLE
Allow users to pass parameters to start_jobs

### ISSUE THREAD

**Issue by FabioRosado** [coiled/feedback#137]
While chatting with José Morales, he asked if it was possible to pass parameters to the `start_job` command. In specific it would be good to allow users to submit files to this command without the need to recreate a cluster configuration.

It would be good to have a Job constructor similar to the Cluster one that would allow us to modify a job's configuration on the fly.

**Comment by jose-moralez** [comment]
I believe jobs are kind of designed for notebooks right now, but I find them very useful for batch processing-style kind of workloads, specially since they're kind of fire-and-forget so you can have an automated process call `coiled.start_job` and just forget about it (with a lambda, for example). These kind of workloads involve running a script (which would be uploaded via the `files` argument of  `coiled.create_job_configuration`), however I think those scripts are hardly static, so having to specify `command` in the job configuration feels very unflexible. I'd like to be able to specify `command` in `coiled.start_job` instead or even being able to upload files with it (in case your script takes in a configuration file instead of arguments).

**Comment by shughes-uk** [comment]
jobs is deprecated
