### ISSUE TITLE
Clusters stopped getting workers

### ISSUE THREAD

**Issue by mrocklin** [coiled/feedback#152]
I've been bringing up clusters all day today (thanks by the way, this is great).  However recently my clusters have stopped getting workers.  My worker count sits at 0/50 for 5-10 minutes.

Scheduler name: mrocklin-cbf03a69-a

I've just switched from hosted AWS to hosted GCP to see if that resolves the problem.

**Comment by mrocklin** [comment]
Workers are coming up in GCP, although slowly.

**Comment by FabioRosado** [comment]
I've had a quick look on the logs and it seems that the reason why workers stopping showing is because AWS didn't have any more instances available.

We have an [issue](https://gitlab.com/coiled/cloud/-/issues/3174) to handle the `InsufficientInstanceCapacity` better in the short term and then rework our VPC setup should solve most of this problem

**Comment by mrocklin** [comment]
Good to know.  It was great being able to switch clouds in this case.
