### ISSUE TITLE
Static outbound IP(s) for scheduler/worker in AWS bring-your-own-network

### ISSUE THREAD

**Issue by lfraker** [coiled/feedback#233]
**Description**

We have data sources currently protected by IP filtering, so we need persistent static IPs. I'm running into an issue when trying to follow the recommendation here: https://github.com/coiled/feedback/issues/232#issuecomment-1472667032

I was able to create the private subnet and NAT Gateway resources, but when creating the Coiled cluster, there was no instance type availability in the requested availability zone. It seems like when you let Coiled setup your VPC resources, it deploys a subnet in each availability zone to get around limited instance availability in one (then chooses a subnet at the time of creating instances). I'd be happy to create multiple private subnets across availability zones, but it doesn't seem like I can specify a list of worker/scheduler subnets in either the Coiled portal or when specifying 'network' config in the set_backend_options function. Please let me know if I'm missing something, or if there's another way to accomplish this?

Separately, the Coiled docs call out that 'It’s necessary that the scheduler and workers be able to download software (as well of course as any data used in your computations).' https://docs.coiled.io/user_guide/tutorials/bring_your_own_network.html#network-requirements
If I can resolve the above availability zone issue, I can guarantee a persistent static IP for the workers. However, how would you recommend I accomplish this for the scheduler (or did I misinterpret the docs and the scheduler doesn't need access to the data)?
I have no issue with Coiled generating public IPs (for schedulers or workers), but are those guaranteed to persist even after the cluster is spun down from inactivity - it doesn't seem like Coiled is creating persistent Elastic IPs, but maybe I'm missing something?

**Comment by ntabris** [comment]
Yes, currently if you're using your own subnet, you can only specify one. Most AZs have pretty good AZ availability, so most likely the short term solution is to make subnet in a different AZ. That's not a great solution though and it definitely does make sense to let the user specify multiple subnets, so we can plan to work on that enhancement.

Coiled doesn't use Elastic IPs. Do you need a fixed IP for scheduler? My guess is not, since I think you needed fixed IP to whitelist access to data source, and I'd expect that only the workers need access to the data source.

This does feel more complicated than it should be, and we'll think about how to make things better for this sort of situation. If it's helpful, I'd be happy to talk over your setup and we can try to get this working on a call—let me know and I can email you a link to scheduler a meeting.

**Comment by ntabris** [comment]
Yes, I can see that same subnet is set for scheduler and workers for you account. I'll try to reproduce and try to get a fix soon.

If you'd like, I can manually set the scheduler subnet on your account for a quick fix now.

**Comment by ntabris** [comment]
Hm, I tried replicating and I was able to successfully set separate scheduler and worker subnets.

If you want help debugging, let me know and I can send you a link to schedule a call. Network debugging is often annoying.

**Comment by lfraker** [comment]
Sounds good, let's get on a call - I'm now running into the same timeout when configuring a Coiled-generated VPC as bring-your-own-network. Can you send a scheduling link to: luke@frakerconsulting.com

**Comment by lfraker** [comment]
@ntabris confirming that I was able to resolve the SG issue (and test by deploying everything publicly), so the only remaining issue is the fix to deploy the scheduler to the provided scheduler subnet. Please let me know once you have a fix out that I can test, thanks!

**Comment by ntabris** [comment]
I've tracked down the bug.

Do you mind trying `Cluster(..., use_best_zone=False)` when creating a cluster and see if that gets around the bug?

**Comment by lfraker** [comment]
That fixed it, thanks!

**Comment by ntabris** [comment]
Great! (We'll also get the fix out in the next day or two so that `use_best_zone=False` won't be necessary, but glad you're unblocked for now.)
