### ISSUE TITLE
 Software environment exited with error code 1. TypeError: 

### ISSUE THREAD

**Issue by rsignell** [coiled/feedback#277]
I'm trying to start a Coiled notebook with an environment I created and I'm getting:
```
 Software environment exited with error code 1. TypeError: list indices must be integers or slices, not str) (cluster_id: 454392)
```

![image](https://github.com/coiled/feedback/assets/125569335/6cf4a4c8-d12d-4eac-97e7-190b2e98122d)

**Comment by ntabris** [comment]
This is caused by https://github.com/dask/dask/issues/10507

We ship the local dask config to your remote machine, but there was a breaking change to the config schema and the mismatch between the local config schema (that we then ship) and what the remote version of dask wants is causing the problem.

If you're able to re-build your `pangeo` software environment with `dask>=2023.9.2`, that should resolve this. You didn't pin and (for reasons I haven't looked into) got 2023.9.1.

If you specifically need 2023.9.1, let me know and we can figure out another workaround.

**Comment by rsignell** [comment]
@ntabris thanks for that tip!     I have no idea what package in my (rather complex) environment was pinning dask to the older version, but I added `dask>=2023.9.2` and the environment worked fine!

**Comment by ntabris** [comment]
@rsignell glad that worked for you, thanks for letting me know!
