### ISSUE TITLE
Provide Dask configuration for workers and scheduler

### ISSUE THREAD

**Issue by mrocklin** [coiled/feedback#75]
It would be nice to be able to set configuration for the scheduler and workers from the Cluster object or a cluster configuration.

This is useful, for example, when setting default compression.  @quasiben is running into this now.

(we're able to work around it, but it would be nice)

cc @jrbourbeau

**Comment by mrocklin** [comment]
Maybe this?

```python
cluster = coiled.Cluster(
    ...
    worker_config={"distributed": {"comm": {"compression": "blosc"}}},
    scheduler_config={"distributed": {"comm": {"compression": "blosc"}}},
)
```

**Comment by jrbourbeau** [comment]
This seems totally reasonable. I've added it to my queue for later this week

**Comment by FabioRosado** [comment]
Hello folks, I had a quick look at the [Cluster API reference](https://docs.coiled.io/user_guide/api.html#coiled.Cluster) and wondered if the `scheduler_options` and `worker_options` is doing what you suggested Matt? Just wanted to double-check before closing this issue. Thank you 😄

**Comment by jrbourbeau** [comment]
Thanks for asking @FabioRosado, this is a separate issue. `scheduler_options` / `worker_options` are used to specify arguments for `Scheduler.__init__` / `Worker.__init__` to allow for customizing scheduler / worker creation. `worker_config` / `scheduler_config` are to allow for setting [Dask configuration values](https://docs.dask.org/en/latest/configuration.html) on the scheduler / worker machines

**Comment by gjoseph92** [comment]
Small note on the API: since you probably also want to use that config locally, you might already have it set in a yaml file somewhere, so being able to pass the path to a file would be a nice convenience.

Also, we might want logic for dropping the `coiled` part of the config. Passing `config=dask.config.config` might be a tempting way to ensure you have the same config on the cluster as locally, but depending on implementation, could cause collisions with the coiled config vars that get set automatically on the backend.

**Comment by gjoseph92** [comment]
Update: this would be helpful for @jose-moralez to specify worker resources on Coiled.
https://coiled-users.slack.com/archives/C0195GJKQ1G/p1619023637047600

**Comment by FabioRosado** [comment]
Closing this issue as Nat implemented shipping the dask config
